### ISSUE TITLE
Add civilian ship type, give Battleship and Submarine stealth. 

### ISSUE THREAD

**Issue by evan-milton** [OSU-CS361-W17/group6_project3#1]
Need a way of creating a model with Dinghy (Size 1) and Clipper (Size 3). These replace Cruiser and Destroyer. These ships sink if hit just once. 

Battleship and Subs can't be detected by scans.

**Comment by evan-milton** [comment]
I will likely alter the ship class to include a list of types for ships. I will make a child class battleship model that uses the updated mechanics. If a user selects Classic, the original model class is used. If new, the updated class will be used.

**Comment by evan-milton** [comment]
Okay so I've added child classes for Stealth and Civilian ships, and a sub class of Battleship Model called Battleship Model Updated. Classic functions as expected but Updated get request when first hitting page throws 500. It looks like Gson isn't working to convert it to JSON, may be a problem with inheritance. Look over it, see if y'all can't find a bug.

**Comment by evan-milton** [comment]
Trevor has circumnavigated the problem. Gonna close this.

**Comment by orrelln** [comment]
Ships do not properly have stealth mechanic. Needs to be done.

**Comment by TrevorSpear** [comment]
#14 is the fix for this.
